In [1]:
s='14'
a=int(s) #typecasting
print(type(a))

<class 'int'>


Converting list to numpy array: 

In [3]:
import numpy as np
v=[6,54,3,6,4,10]
np.array(v)

array([ 6, 54,  3,  6,  4, 10])

In [4]:
print( np.array(v))  #1D array

[ 6 54  3  6  4 10]


In [5]:
np.array(v).shape  #output means 1 row with 6 elements. 

(6,)

In [12]:
b=[[1,2,3,4,5,6]]   #output means 1 row with 6 columns.
c=np.array(b)
c.shape

(1, 6)

In [6]:
x=np.array(v)
x.shape

(6,)

In [9]:
r=[[1,2,3],[8,5,7],[4,9,0],[3,6,4]]
y=np.array(r)
print(y)
print(y.shape)  #2D array

[[1 2 3]
 [8 5 7]
 [4 9 0]
 [3 6 4]]
(4, 3)


In [18]:
#3D array
s=[ [[1,2,3],[3,2,1],[2,1,3]], [[4,5,6],[5,6,4],[6,4,5]], [[7,8,9],[8,9,7],[9,7,8]] ]
t=np.array(s)
print(t)
print(t.shape)

[[[1 2 3]
  [3 2 1]
  [2 1 3]]

 [[4 5 6]
  [5 6 4]
  [6 4 5]]

 [[7 8 9]
  [8 9 7]
  [9 7 8]]]
(3, 3, 3)


In [21]:
print(np.arange(3,61,3))
print(np.arange(100,50,-10))

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60]
[100  90  80  70  60]


In [22]:
np.zeros(4)

array([0., 0., 0., 0.])

In [24]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [25]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [29]:
np.linspace(1,50) #gives 50 equally spaced nos. in the interval. Note that endpoint is inclusive here.
#read docstring.

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [39]:
x=np.linspace(2,5)
x

array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
       2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
       2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
       2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
       3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
       3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
       3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
       4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
       4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
       4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ])

In [31]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [33]:
np.eye(4,5,-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [36]:
s=np.random.randint(22,57,13)
s

array([51, 27, 23, 49, 47, 36, 28, 41, 36, 37, 55, 29, 55])

In [37]:
s.reshape(13,1)

array([[51],
       [27],
       [23],
       [49],
       [47],
       [36],
       [28],
       [41],
       [36],
       [37],
       [55],
       [29],
       [55]])

In [41]:
x.reshape(25,2)

array([[2.        , 2.06122449],
       [2.12244898, 2.18367347],
       [2.24489796, 2.30612245],
       [2.36734694, 2.42857143],
       [2.48979592, 2.55102041],
       [2.6122449 , 2.67346939],
       [2.73469388, 2.79591837],
       [2.85714286, 2.91836735],
       [2.97959184, 3.04081633],
       [3.10204082, 3.16326531],
       [3.2244898 , 3.28571429],
       [3.34693878, 3.40816327],
       [3.46938776, 3.53061224],
       [3.59183673, 3.65306122],
       [3.71428571, 3.7755102 ],
       [3.83673469, 3.89795918],
       [3.95918367, 4.02040816],
       [4.08163265, 4.14285714],
       [4.20408163, 4.26530612],
       [4.32653061, 4.3877551 ],
       [4.44897959, 4.51020408],
       [4.57142857, 4.63265306],
       [4.69387755, 4.75510204],
       [4.81632653, 4.87755102],
       [4.93877551, 5.        ]])

In [42]:
s.argmax()

10

In [43]:
s.argmin()

2

NumPy operations